version: '3'

volumes:
  postgres_data_test: {}

services:
  fastapi_test:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: myferm_fastapi_test
    container_name: myferm_fastapi_test
    volumes:
      - .:/app
      - /app/.venv/
    env_file:
      - ./.envs/.test/.fastapi
    depends_on:
      - postgres_test
    command: pytest

  postgres_test:
    image: postgres:12
    container_name: myferm_postgres_test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.envs/.test/.postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
