"""Added product model

Revision ID: 2bc0e59f7ac6
Revises: 90b7dcc3d0c0
Create Date: 2021-09-03 12:11:46.868160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc0e59f7ac6'
down_revision = '90b7dcc3d0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_types_id'), 'product_types', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.Column('type_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['product_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_types_id'), table_name='product_types')
    op.drop_table('product_types')
    # ### end Alembic commands ###
