"""Added product zone model

Revision ID: 33db04ac8224
Revises: ac80976b3642
Create Date: 2021-09-02 12:11:25.337177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33db04ac8224'
down_revision = 'ac80976b3642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_zone',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('zone_id', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_zone_id'), 'product_zone', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_zone_id'), table_name='product_zone')
    op.drop_table('product_zone')
    # ### end Alembic commands ###
