"""edit job model

Revision ID: 3c41d5cb9e55
Revises: ef27c95fa949
Create Date: 2021-08-18 13:53:44.746113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c41d5cb9e55'
down_revision = 'ef27c95fa949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('product_zone_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'product_zone', ['product_zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'product_zone_id')
    # ### end Alembic commands ###
