"""create missing fields

Revision ID: e07de9f3ea38
Revises: 77ee92002451
Create Date: 2021-09-02 12:29:19.246671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9e4baa40a2'
down_revision = 'e07de9f3ea38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
