"""Added product zone model

Revision ID: e264ff912bca
Revises: 1de22aa893d7
Create Date: 2021-09-03 14:02:17.368261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e264ff912bca'
down_revision = '1de22aa893d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_zone',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('zone_id', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_zone_id'), 'product_zone', ['id'], unique=False)
    op.add_column('jobs', sa.Column('product_zone_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'product_zone', ['product_zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'product_zone_id')
    op.drop_index(op.f('ix_product_zone_id'), table_name='product_zone')
    op.drop_table('product_zone')
    # ### end Alembic commands ###
