"""edit prodcut model

Revision ID: ef27c95fa949
Revises: 42fff00d1283
Create Date: 2021-08-13 15:51:56.717035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef27c95fa949'
down_revision = '42fff00d1283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
