#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Let the DB start
python /app/db/wait_for_db.py

# Run migrations
alembic upgrade head

# Create initial data in DB
python /app/db/init_db.py

exec "$@"

